driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  image: ubuntu-upstart:14.04
  run_command: /sbin/init

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.21.12
  attributes:
    java:
      jdk_version: 8

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[zipkin::default]
